name: Chap Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TARGET_URL: ${{ secrets.TARGET_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Playwright Browsers
        run: dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install chromium

      - name: Run notifier
        run: dotnet run --project ./ChapNotifier

      - name: Upload chapter log artifact
        uses: actions/upload-artifact@v4
        with:
          name: chapter-log
          path: ~/.config/chap_notifier/chapter_log.txt
