name: Chap Notifier Worker

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run app
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: dotnet run --project ./ChapNotifier.csproj --configuration Release
