name: Chap Notifier

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TARGET_URL: ${{ secrets.TARGET_URL }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      # ✅ Download previous chapter_log.txt artifact if exists
      - name: Download previous log
        uses: actions/download-artifact@v4
        with:
          name: chapter-log
          path: ~/.config/chap_notifier
        continue-on-error: true  # Avoid failure if first run

      # ✅ Cache Playwright browsers (optional optimization)
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-chromium

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # ✅ Build and install Playwright
      - name: Build and install Playwright
        run: |
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install chromium

      # ✅ Run notifier
      - name: Run notifier
        run: dotnet run

      # ✅ Upload updated chapter_log.txt as artifact
      - name: Upload updated log
        uses: actions/upload-artifact@v4
        with:
          name: chapter-log
          path: ~/.config/chap_notifier/chapter_log.txt
          overwrite: true
